substitutions:
  devicename: "devkit-s-r"
  
esphome:
  name: $devicename
  friendly_name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: " "
  password: ""

  ap:
  
  reboot_timeout: 0s
  fast_connect: true
  
captive_portal:

web_server:
  port: 80
  css_url: v3
  include_internal: True
  local: True
  version: 2


external_components:
    - source: github://Hasatio/esphome
      components: [posture_analyzer]
      refresh: always


posture_analyzer:
  gain: 1.0
  bluetooth: $devicename


sensor:
  # - platform: posture_analyzer
  #   sample:
  #     name: sample

  - platform: posture_analyzer
    sample_sec:
      name: sample_sec


button:
  - platform: restart
    name: "Restart"


light:
  - platform: status_led
    name: "status led"
    id: status
    pin: 
      number: GPIO13
      mode:
        output: True
      inverted: False
