substitutions:
  devicename: "hydroponics"

esphome:
  name: $devicename
  friendly_name: $devicename
  # on_boot:
  #   - lambda: |-
  #       id(my_ota).set_auth_password("");

esp32:
  board: esp32-gateway
  framework:
    type: arduino
    version: 2.0.11

# Enable logging
logger:

# Enable Home Assistant API
api:
  # encryption:
  #   key: "V9+MQ4tYb7ZCHFnhyWMQNNzwPPE5GOTjB1/81/F2e7A="

ota:
  # password: "f5504587974ff2df678dd129be723ca9"

wifi:
  ssid: !secret wifi_ssid2
  password: !secret wifi_password2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: $devicename

  fast_connect: true
  power_save_mode: none
captive_portal:

web_server:
  port: 80
  css_url: v3
  include_internal: True
  local: True
  version: 2

# i2c:
#   id: i2c0
#   sda: GPIO16
#   scl: GPIO32
#   scan: True


# tca9548a:
#   - address: 0x70
#     id: multiplex0
#     i2c_id: i2c0
#     channels:
#       - bus_id: multiplex0channel0
#         channel: 0
#       - bus_id: multiplex0channel1
#         channel: 1
#       - bus_id: multiplex0channel2
#         channel: 2
#       - bus_id: multiplex0channel3
#         channel: 3
#       - bus_id: multiplex0channel4
#         channel: 4
#       - bus_id: multiplex0channel5
#         channel: 5
#       - bus_id: multiplex0channel6
#         channel: 6
#       - bus_id: multiplex0channel7
#         channel: 7


# ezo_pmp:
#   id: ezo_pmp0
#   address: 0x67  # Default Address for the EZO-PMP.
#   i2c_id: multiplex0channel1
#   update_interval: 1s    

# ads1115:
#   - address: 0x48
#     i2c_id: multiplex0channel2
#     id: ads1115_hub0
#     continuous_mode: True


# pca9685:
#   - id: pca9685_hub0
#     i2c_id: multiplex0channel0
#     frequency: 1500


# # pca9685custom:
# #   - id: pca9685custom_hub0
# #     address: 0x40
# #     i2c_id: multiplex0channel0
# #     frequency: 1500


external_components:
  - source: github://Hasatio/esphome
    components: [water_quality]
    refresh: always

water_quality:
  id: water
  calibration:
    x1: [1,2,3,4,5,6,7,8]
    y1: [10,20,30,40,50,60,70,80]


sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: water_quality
    pump_total:
      id: pump_total
    pump_status:
      id: pump_status
    analog_output:
      id: analog_output

  # - platform: ads1115
  #   multiplexer: A0_GND
  #   ads1115_id : ads1115_hub0
  #   gain: 6.144
  #   name: "ADS1115 1"
  #   id: "ADS1115_1"
  #   update_interval: 0ms

  # # - platform: ezo_pmp
  # #   pump_voltage:
  # #     id: pump_voltage
  # #     name: Pump Voltage

  # # - platform: ezo_pmp
  # #   max_flow_rate:
  # #     id: max_flow_rate
  # #     name: Max Flow Rate
      
  # # - platform: ezo_pmp
  # #   last_volume_requested:
  # #     id: last_volume_requested
  # #     name: Last Volume Requested

  # # - platform: ezo_pmp
  # #   absolute_total_volume_dosed:
  # #     id: absolute_total_volume_dosed
  # #     name: Absolute Total Volume Dosed
      
  # # - platform: ezo_pmp
  # #   total_volume_dosed:
  # #     id: total_volume_dosed
  # #     name: Total Volume Dosed
      
  # # - platform: ezo_pmp
  # #   current_volume_dosed:
  # #     id: current_volume_dosed
  # #     name: Current Volume Dosed


button:
  - platform: restart
    name: "Restart"
    
  # # - platform: template
  # #   name: "Dose Over Time"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.dose_volume_over_time:
  # #         id: ezo_pmp0
  # #         volume: !lambda |-
  # #                 return id(volume).state;
  # #         duration: !lambda |-
  # #                 return id(duration).state;

  # # - platform: template
  # #   name: "Dose Flow Rate"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.dose_with_constant_flow_rate:
  # #         id: ezo_pmp0
  # #         volume_per_minute: !lambda |-
  # #           return id(volume).state;
  # #         duration: !lambda |-
  # #           return id(duration).state;

  # # - platform: template
  # #   name: "Dose Pause"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.pause_dosing:
  # #         id: ezo_pmp0

  # # - platform: template
  # #   name: "Dose Stop"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.stop_dosing:
  # #         id: ezo_pmp0
       
  # # - platform: template
  # #   name: "Dose Set Calibration"
  # #   on_press:
  # #     then:   
  # #     - ezo_pmp.set_calibration_volume:
  # #         id: ezo_pmp0
  # #         volume: !lambda |-
  # #           return id(calibration).state;
    
  # # - platform: template
  # #   name: "Dose Clear Calibration"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.clear_calibration:
  # #         id: ezo_pmp0

  # # - platform: template
  # #   name: "Dose Clear Total Volume"
  # #   on_press:
  # #     then:
  # #     - ezo_pmp.clear_total_volume_dosed:
  # #         id: ezo_pmp0
       
  # # - platform: template
  # #   name: "Dose Continuously"
  # #   on_press:   
  # #     then:
  # #     - ezo_pmp.find:
  # #         id: ezo_pmp0

  # - platform: template
  #   name: "Dose Volume"
  #   on_press:   
  #     then:
  #     - ezo_pmp.dose_volume:
  #         id: ezo_pmp0
  #         volume: !lambda |-
  #           return id(volume).state;

  # # - platform: template
  # #   name: "Dose Volume"
  # #   on_press:   
  # #     then:
  # #     - pca9685custom.dose_volume:
  # #         id: pca9685custom_hub0
  # #         volume: !lambda |-
  # #           return id(volume).state;


switch:
  - platform: gpio
    name: "Led"
    pin: 
      number: GPIO33
      mode:
        output: True
      inverted: False


# status_led:
#     pin: 
#       number: GPIO33
#       mode: 
#         output: True
#       inverted: False


light:
  - platform: status_led
    name: "status led"
    id: status
    pin: 
      number: GPIO33
      mode:
        output: True
      inverted: False
    on_state:
      if:
        condition:
          wifi.connected:
        then:
        - light.turn_on: 
            id: led
            # effect: strobe
        else:
        - light.turn_off: 
            id: led
    on_turn_off:
      if:
        condition:
          wifi.connected:
        then:
        - light.turn_on: 
            id: led
            # effect: strobe
        else:
        - light.turn_off: 
            id: led

  - platform: binary
    name: "led"
    id: led
    output: out
    # effects:
    #   - strobe:
    #       name: strobe
    #       colors:
    #         - state: true
    #           brightness: 100%
    #           duration: 100ms
    #         - state: false
    #           duration: 50ms
    #         - state: true
    #           brightness: 100%
    #           duration: 100ms
    #         - state: false
    #           duration: 200ms


output:
  - platform: gpio
    id: out
    pin: 
      number: GPIO33
      mode:
        output: True
      inverted: False

#   - platform: pca9685
#     id: pwm0
#     pca9685_id: pca9685_hub0
#     channel: 0

#   - platform: pca9685
#     id: pwm1
#     pca9685_id: pca9685_hub0
#     channel: 1

#   # - platform: pca9685custom
#   #   id: pwm0
#   #   pca9685custom_id: pca9685custom_hub0
#   #   channel: 0

#   # - platform: pca9685custom
#   #   id: pwm1
#   #   pca9685custom_id: pca9685custom_hub0
#   #   channel: 1

#   - platform: pca9685
#     id: pwm4
#     pca9685_id: pca9685_hub0
#     channel: 4

#   - platform: pca9685
#     id: pwm5
#     pca9685_id: pca9685_hub0
#     channel: 5

#   - platform: pca9685
#     id: pwm6
#     pca9685_id: pca9685_hub0
#     channel: 6

#   - platform: pca9685
#     id: pwm7
#     pca9685_id: pca9685_hub0
#     channel: 7

#   - platform: pca9685
#     id: pwm12
#     pca9685_id: pca9685_hub0
#     channel: 12

#   - platform: pca9685
#     id: pwm13
#     pca9685_id: pca9685_hub0
#     channel: 13

#   - platform: pca9685
#     id: pwm14
#     pca9685_id: pca9685_hub0
#     channel: 14

#   - platform: pca9685
#     id: pwm15
#     pca9685_id: pca9685_hub0
#     channel: 15
    
#   - platform: ledc
#     id: pwm
#     pin: 13


# fan:
#   - platform: hbridge
#     id: motor1
#     name: "motor1"
#     pin_a: pwm0
#     pin_b: pwm1
#     # enable_pin: motor_enable
#     decay_mode: fast   # slow decay mode (braking) or fast decay (coasting).
    
#   - platform: hbridge
#     id: test1
#     name: "test1"
#     pin_a: pwm4
#     pin_b: pwm5
#     # enable_pin: motor_enable
#     decay_mode: slow   # slow decay mode (braking) or fast decay (coasting).

#   - platform: hbridge
#     id: test2
#     name: "test2"
#     pin_a: pwm6
#     pin_b: pwm7
#     # enable_pin: motor_enable
#     decay_mode: fast   # slow decay mode (braking) or fast decay (coasting).

#   - platform: hbridge
#     id: test3
#     name: "test3"
#     pin_a: pwm12
#     pin_b: pwm13
#     # enable_pin: motor_enable
#     decay_mode: slow   # slow decay mode (braking) or fast decay (coasting).

#   - platform: hbridge
#     id: test4
#     name: "test4"
#     pin_a: pwm14
#     pin_b: pwm15
#     # enable_pin: motor_enable
#     decay_mode: fast   # slow decay mode (braking) or fast decay (coasting).


# number:
  # - platform: template
  #   id: motor
  #   name: "Motor"
  #   optimistic: true
  #   min_value: -100
  #   max_value: 100
  #   initial_value: 0
  #   step: 1

  # - platform: template
  #   id: volume
  #   name: "Volume"
  #   optimistic: true
  #   min_value: -100
  #   max_value: 100
  #   initial_value: 0
  #   step: 0.01

  # - platform: template
  #   id: duration
  #   name: "Duration"
  #   optimistic: true
  #   min_value: 0
  #   max_value: 100
  #   initial_value: 0
  #   step: 1

  # - platform: template
  #   id: calibration
  #   name: "Calibration Value"
  #   optimistic: true
  #   min_value: 0
  #   max_value: 10000
  #   step: 0.01


# text_sensor:
  # - platform: ezo_pmp
  #   dosing_mode:
  #     id: dosing_mode
  #     name: Dosing Mode
  # - platform: ezo_pmp
  #   calibration_status:
  #     id: calibration_status
  #     name: Calibration Status


# binary_sensor:
  # - platform: ezo_pmp
  #   is_paused:
  #     id: is_paused
  #     name: Is Paused

  # - platform: ezo_pmp
  #   pump_state:
  #     id: pump_state
  #     name: Pump State    

    